# Generated by Django 5.0.1 on 2024-02-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='BlogModel',
        ),
    ]
