# Generated by Django 5.0.1 on 2024-02-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogs_blogmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
    ]
